DROP DATABASE IF EXISTS thyme2eat;
CREATE DATABASE thyme2eat;

CREATE TABLE jokes;

INSERT INTO jokes (text)
VALUES(
  "Just burned 2,000 calories. That's the last time I leave brownies in the oven while I nap",
  "Smoking will kill you. Bacon will kill. But, smoking bacon  will cure it",
  "I eat my tacos over a Tortilla. That way when stuff falls out, BOOM, another taco",
  "Why do the French eat snails? They don't like fast food",
  "One day you're the best thing since sliced brea. The next, you're toast",
  "I've just written a song about tortillas...actually, it's more of a wrap",
  "Justice is a dish best served cold because if it were served warm, it would be justwater",
  "For Halloween we dressed up as almonds. Everyone could tell we were nuts",
  "What happens if you eat yeast and shoe polish? Every morning you will rise and shine",
  "Why do seagulls fly over the sea? Because if they flew over the bay they'd be bagels",
  "I've started telling everyone about the benefits of eating dried grapes. It's all about raisin awareness",
  "I always knock on the fridge before I open it. Just in case there's a salad dressing",
  "What do you call an academically successful slice of bread? An honor roll",
  "I've become such a bad cook that I'm able to use the smoke alarm as a timer",
  "I had a joke to tell about pizza, but everyone says it's too cheezy"
)